### ISSUE TITLE
Getting Wrong order of the bboxes. Am I doing something wrong here?

### ISSUE THREAD

**Issue by vikas-singh16** [ppaanngggg/layoutreader#10]
Hi,
I tested this model on my input data which is the output of a layout detection model which is 
"{{'boxes': [[95, 857, 816, 1804],
  [870, 1473, 1505, 1815],
  [869, 656, 1505, 997],
  [275, 270, 654, 730],
  [949, 287, 1486, 580],
  [969, 1078, 1443, 1405],
  [908, 1882, 1510, 2050],
  [281, 152, 1525, 230],
  [111, 778, 796, 852],
  [60, 61, 276, 278],
  [180, 1817, 733, 1892],
  [59, 2057, 744, 2112],
  [350, 1913, 531, 2048],
  [887, 1012, 1486, 1046],
  [886, 1826, 1486, 1859],
  [1351, 2073, 1515, 2105],
  [403, 79, 1356, 130],
  [866, 611, 1395, 649],
  [867, 1431, 1351, 1467],
  [399, 693, 524, 728]],
 'texts': ['table',
  'table',
  'table',
  'figure',
  'figure',
  'figure',
  'plain text',
  'plain text',
  'plain text',
  'abandon',
  'plain text',
  'abandon',
  'figure',
  'plain text',
  'plain text',
  'abandon',
  'title',
  'title',
  'table_caption',
  'figure_caption'],
 'width': 1675,
 'height': 2175}"

Its annotated image looks like this,
![Annotated_img](https://github.com/user-attachments/assets/b133dce3-bdb5-402d-a878-e494ab3db357)

After using the model , I am getting an output like this,
![Annotaed_with_wrong_order](https://github.com/user-attachments/assets/27562dcd-cc19-42af-8f5e-4a4abcc6cfb2)

Am I doing something wrong here, I am using the same code as provided. So can u pls have a look.

**Comment by ppaanngggg** [comment]
I am so sorry, this model is trained for text spans, not layout bboxes.

If you want to predict orders of layout bboxes, you can try surya, it has a model for you.  https://github.com/VikParuchuri/surya

**Comment by vikas-singh16** [comment]
Thank you so much for your quick response and the repository you provided. Do you have any suggestions for datasets that include reading order information for layout detection bounding boxes?

**Comment by ppaanngggg** [comment]
I didn't find a existing dataset, maybe you need to annotate by yourself or build a new dataset from some layoutreader dataset by some rules.
