### ISSUE TITLE
框架结构

### ISSUE THREAD

**Issue by MovePhilip** [ppaanngggg/layoutreader#2]
我想知道你的这种预测方式最终效果会好吗？

**Comment by chinaphilip** [comment]
还有你的框架里面seq2seq is too slow in production, I want to get the all predictions in one pass.这个你实现了吗

**Comment by MovePhilip** [comment]
看完代码，我只能说这位兄台真的6

**Comment by ppaanngggg** [comment]
额，我把我的评测指标什么的都写在readme里了，你看下能不能满足你的业务指标吧，我搞这个也是被逼无奈
