### ISSUE TITLE
Licensing and training a variant suitable for commercial use

### ISSUE THREAD

**Issue by shoshinL** [ppaanngggg/layoutreader#3]
Hi Hantian Pang,

I love this project. I'm a Univeristy student from Germany and have the following questions:

1. As this is a fine-tune of LayoutLMv3 I cannot use this in a commercial project, right?
2. When trying to implement an approach like this, using only the bbox coordinates, but using a model with a more permissive license, like LiLT, do you think it could work? Could you disclose what you used to train, as I'd like to know if I need to have access to some strong GPU.

Thanks in advance for the answers!

**Comment by ppaanngggg** [comment]
1. Thanks for your question, I found it use CC-BY-NC-SA, so it can't be used in commerical project. And I update LICENSE file now.
2. Great advice, I think LiLT works, you can have a try. I train by 8*RTX3090, you can rent cheep GPUs from [vast.ai](https://vast.ai)

**Comment by ppaanngggg** [comment]
@shoshinL do you need any other help? If not, I will close this issue.

**Comment by shoshinL** [comment]
I don't have any further questions.
Thank you for your help and this great repo!

**Comment by mllife** [comment]
@shoshinL , I am also facing similar issue. Did you make any progress? Trained LiLT? Can you share your model? Also @ppaanngggg I have a question, do the https://github.com/doc-analysis/ReadingBank ReadingBank dataset have license restriction?

**Comment by ppaanngggg** [comment]
I think you just can't re-distribute or sell this dataset. It should be OK to train your own models.

**Comment by mllife** [comment]
@shoshinL , can you tell what solution you end up with ?

**Comment by shoshinL** [comment]
> @shoshinL , can you tell what solution you end up with ?

@mllife Sorry for the late reply. Sadly, I'm not permitted to say publicly. We didn't end up training LiLt.

More generally, I don't know of any large datasets other than ReadingBank for reading order specifically. If it's more about grouping information maybe take a look at ppaanngggg's DocLayNet project using yolo (or train a similar one using the yoloMIT project for commercial license). If you haven't checked out Nils Rogge's examples yet I also recommend looking through those, as he's usually really up to date with these kinds of use cases.
