### ISSUE TITLE
对block区块的排序效果较差

### ISSUE THREAD

**Issue by myhloli** [ppaanngggg/layoutreader#5]
不知道这个模型是不是因为训练数据是基于span级别或者line级别的，我使用block级别的块尝试排序，发现效果较差
![image](https://github.com/user-attachments/assets/828387cd-c36b-493f-a031-7bcdefe96c52)
![image](https://github.com/user-attachments/assets/2915884c-451f-4a92-bccc-5efc4b73f697)
![image](https://github.com/user-attachments/assets/758d8eba-6094-43b6-ae2e-2ce00d2d1681)
![image](https://github.com/user-attachments/assets/c453d01e-1ee9-41fa-8ce4-de3b962f1375)

我会尝试再使用line级别的bbox进行排序，看看结果有没有改善

**Comment by ppaanngggg** [comment]
是的, 是基于line级别的数据训练的.

严格来说, 是根据word级别的数据合成的line级别的数据. 所以你可以考虑用类似的策略, 合成block级别的数据来训练试试.

**Comment by ppaanngggg** [comment]
https://github.com/VikParuchuri/surya

可以试试这个

**Comment by myhloli** [comment]
用line重试了这个项目，效果确实不错
![img_v3_02f3_80d66820-cb60-4bf1-b3ed-f2198a32c82g](https://github.com/user-attachments/assets/920f31bd-a8c8-4244-bbba-907ab11382ae)
![img_v3_02f3_4c48bce9-4dd3-45f2-9c3d-e074140fd85g](https://github.com/user-attachments/assets/051ada32-817a-49b9-8a27-f8aee23adbf0)
![img_v3_02f3_ede66ead-3086-44b4-b458-704855ea671g](https://github.com/user-attachments/assets/94fce24b-b447-4d01-a85c-736d2661c1de)
![img_v3_02f3_bec84b00-2c54-48eb-8d46-5bec40c8199g](https://github.com/user-attachments/assets/841d6a11-7e20-4915-8a9b-b572a3b58193)
![img_v3_02f3_0219535c-5e2a-45a2-8ad7-03ede4399fcg](https://github.com/user-attachments/assets/43417428-cb50-4a9f-a89d-36e99562cb79)
对于图文混合，三列及以上的排序准确度很高，
另外发现两个badcase
![img_v3_02f3_9250baaf-e27d-4bd3-a23a-4b281284763g](https://github.com/user-attachments/assets/e3837bab-f21e-4583-a3f6-62ab7b2baf63)
![img_v3_02f3_ab8b44e9-500d-4818-9750-53940cf1d2dg](https://github.com/user-attachments/assets/23224af6-d1fb-41ab-993a-b3021bb104a1)
![image](https://github.com/user-attachments/assets/0e29df71-1ec4-40f2-96d5-6b39f8630506)

总体上已经达到可用级别了。

对于block的排序我这边暂时的思路是先将line fill进block，每个block根据line序号的平均值进行排序，最终实现block的排序

**Comment by ppaanngggg** [comment]
对的, 我之前也是这么用的, 因为缺少优质的block级别的排序数据, 然后我这个模型反正也已经训好了, 跑得也挺快

**Comment by ppaanngggg** [comment]
block检测试试这个 https://github.com/ppaanngggg/yolo-doclaynet

**Comment by myhloli** [comment]
> block检测试试这个 https://github.com/ppaanngggg/yolo-doclaynet

block检测我们目前用的https://github.com/opendatalab/PDF-Extract-Kit
基于layoutlmv3微调的版本，得益于大量预标注的数据，这套layout检测效果非常好

**Comment by ppaanngggg** [comment]
> > block检测试试这个 https://github.com/ppaanngggg/yolo-doclaynet
> 
> block检测我们目前用的https://github.com/opendatalab/PDF-Extract-Kit 基于layoutlmv3微调的版本，得益于大量预标注的数据，这套layout检测效果非常好

高科技，可以想像，肯定是这个效果更好

**Comment by wawaa** [comment]
哈哈最近有个上海AI lab 出的基于YOLO 的layout检测，速度和效果也可以。
