### ISSUE TITLE
希望能将模型文件上传到modelscope

### ISSUE THREAD

**Issue by myhloli** [ppaanngggg/layoutreader#6]
我们计划在项目 https://github.com/opendatalab/MinerU 中使用这个模型，
考虑到国内用户较多，希望您能将模型文件在modelscope上也上传一份，感激不尽。

**Comment by ppaanngggg** [comment]
好啊, 没问题, 我国庆节搞一下, 如果接入了麻烦加一个链接地址, 感谢

**Comment by myhloli** [comment]
> 好啊, 没问题, 我国庆节搞一下, 如果接入了麻烦加一个链接地址, 感谢

👌

**Comment by ppaanngggg** [comment]
https://www.modelscope.cn/models/ppaanngggg/layoutreader

看看是不是可以了

**Comment by myhloli** [comment]
> https://www.modelscope.cn/models/ppaanngggg/layoutreader
> 
> 看看是不是可以了

可以了，现在已经集成到dev分支了，readme在dev分支已加链接，预计月底release会同步到master。
