### ISSUE TITLE
Why does tools.py remove valid bboxes?

### ISSUE THREAD

**Issue by cnr0724** [ppaanngggg/layoutreader#7]
I tried to preprocess my own dataset, but I realized that the length of the input box list and the length of the output box list are different. When I checked `tools.py`, I realized that the code skips preprocessing bboxes according to their coordinates.
https://github.com/ppaanngggg/layoutreader/blob/f0718ca2144a8238d18985eda1628f80dc6ae5d1/tools.py#L54-L56
As ReadingBank uses the bbox format(xywh), this line can actually remove the valid bboxes if the value of w or h is smaller than x or y.
As far as I checked, there were no preprocessing part that changes the bbox format(xywh) to box format(xyxy) or vice versa in this code. Is this intended?

**Comment by cnr0724** [comment]
Found out I was wrong haha....I'm sorry. ReadingBank is based on box format. I'll close this issue.

**Comment by ppaanngggg** [comment]
ReadingBank is based on token
