### ISSUE TITLE
加入文字信息

### ISSUE THREAD

**Issue by huihuiustc** [ppaanngggg/layoutreader#8]
请问如果想要加入文字信息来辅助训练的话，楼主可以给出一些参考意见吗？我看目前是直接_input_ids放进去的是UNK_TOKEN_ID=3，我可以直接把每一个文本框对应的字符放进去吗？

**Comment by ppaanngggg** [comment]
那不可以噢，需要优化代码了，你没法表示一段文字是什么token，需要改成一个span的所有token的embedding聚合成一个span的embedding作为输入

**Comment by ppaanngggg** [comment]
您好，还有什么问题吗，没有的话我关掉issue了

**Comment by huihuiustc** [comment]
没有了，没有了，我差不多改好了，精度又提升了一点点

**Comment by cloudfool** [comment]
> 没有了，没有了，我差不多改好了，精度又提升了一点点
请问 具体是如何做的呢？

**Comment by cloudfool** [comment]
> 那不可以噢，需要优化代码了，你没法表示一段文字是什么token，需要改成一个span的所有token的embedding聚合成一个span的embedding作为输入

请问如何聚合成一个span的embedding？ 谢谢

**Comment by ppaanngggg** [comment]
> > 那不可以噢，需要优化代码了，你没法表示一段文字是什么token，需要改成一个span的所有token的embedding聚合成一个span的embedding作为输入
> 
> 请问如何聚合成一个span的embedding？ 谢谢

可以直接一个span中所有token的embedding取平均

**Comment by milk333445** [comment]
> > > 那不可以噢，需要优化代码了，你没法表示一段文字是什么token，需要改成一个span的所有token的embedding聚合成一个span的embedding作为输入
> > 
> > 
> > 请问如何聚合成一个span的embedding？ 谢谢
> 
> 可以直接一个span中所有token的embedding取平均

想請問如果要實現span中所有token的embedding取平均，因為這個任務是使用LayoutLMv3ForTokenClassification，它實現文字跟框embedding融合是寫在LayoutLMv3TextEmbeddings當中，我想到的方法是重新覆寫LayoutLMv3TextEmbeddings中的forward嗎(重寫embedding那段的邏輯)，請問是否有其他更簡便或推薦的方法呢，謝謝!

**Comment by ppaanngggg** [comment]
> 想請問如果要實現span中所有token的embedding取平均，因為這個任務是使用LayoutLMv3ForTokenClassification，它實現文字跟框embedding融合是寫在LayoutLMv3TextEmbeddings當中，我想到的方法是重新覆寫LayoutLMv3TextEmbeddings中的forward嗎(重寫embedding那段的邏輯)，請問是否有其他更簡便或推薦的方法呢，謝謝!

另外一种方法呢是重复bbox，比如一个span里有10个token，那就把这个span的bbox在数据上重复10次。劣势是：
1. 你需要重新实现一下后处理的逻辑
2. 由于模型是bert架构的，目前是512个token上限，按照这种方式，在1页文字token超出512后，不得不使用其他的方式来切分token再输入模型

**Comment by milk333445** [comment]
> > 想請問如果要實現span中所有token的embedding取平均，因為這個任務是使用LayoutLMv3ForTokenClassification，它實現文字跟框embedding融合是寫在LayoutLMv3TextEmbeddings當中，我想到的方法是重新覆寫LayoutLMv3TextEmbeddings中的forward嗎(重寫embedding那段的邏輯)，請問是否有其他更簡便或推薦的方法呢，謝謝!
> 
> 另外一种方法呢是重复bbox，比如一个span里有10个token，那就把这个span的bbox在数据上重复10次。劣势是：
> 
> 1. 你需要重新实现一下后处理的逻辑
> 2. 由于模型是bert架构的，目前是512个token上限，按照这种方式，在1页文字token超出512后，不得不使用其他的方式来切分token再输入模型

了解，那bbox重複的部分，應該就不會計算loss，label直接補成-100這樣嗎，還是都會參與loss計算，我看LayoutLMv3ForTokenClassification原本的推理方式好像就會這樣補，謝謝!

**Comment by ppaanngggg** [comment]
你可以参考下原始的版本，他就是这么实现的，具体loss怎么计算的我已经忘了，应该是算进去的，相当于输出是1111，2222这样。
